# Import Data

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
import os
print(os.listdir())

['.ipynb_checkpoints', 'hotel.py1.ipynb', 'movies.ipynb', 'movies1.ipynb', 'movies2.ipynb', 'superstore.ipynb', 'winemag-data.ipynb']

In [6]:
import os

for root, dirs, files in os.walk(r"C:\Users\siddh"):
    for file in files:
        if "winemag" in file.lower() and file.endswith(".csv"):
            print(os.path.join(root, file))

C:\Users\siddh\Downloads\archive (2)\winemag-data-130k-v2.csv
C:\Users\siddh\Downloads\archive (2)\winemag-data_first150k.csv
C:\Users\siddh\Downloads\archive (2)\.ipynb_checkpoints\winemag-data_first150k-checkpoint.csv

# Load the Data

In [7]:
df = pd.read_csv(r"C:\Users\siddh\Downloads\archive (2)\winemag-data-130k-v2.csv")

# Data Understanding

In [8]:
df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [9]:
df.tail()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
129966,129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [10]:
df.columns

Index(['Unnamed: 0', 'country', 'description', 'designation', 'points',
       'price', 'province', 'region_1', 'region_2', 'taster_name',
       'taster_twitter_handle', 'title', 'variety', 'winery'],
      dtype='object')

In [11]:
df.shape

(129971, 14)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129971 entries, 0 to 129970
Data columns (total 14 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             129971 non-null  int64
 1   country                129908 non-null  object
 2   description            129971 non-null  object
 3   designation            92506 non-null   object
 4   points                 129971 non-null  int64
 5   price                  120975 non-null  float64
 6   province               129908 non-null  object
 7   region_1               108724 non-null  object
 8   region_2               50511 non-null   object
 9   taster_name            103727 non-null  object
 10  taster_twitter_handle  98758 non-null   object
 11  title                  129971 non-null  object
 12  variety                129970 non-null  object
 13  winery                 129971 non-null  object
dtypes: float64(1), int64(2), object(11)
memory usage: 13.9+ MB

In [14]:
df.describe()

          Unnamed: 0         points          price
count  129971.000000  129971.000000  120975.000000
mean    64985.000000      88.447138      35.363389
std     37519.540256       3.039730      41.022218
min         0.000000      80.000000       4.000000
25%     32492.500000      86.000000      17.000000
50%     64985.000000      88.000000      25.000000
75%     97477.500000      91.000000      42.000000
max    129970.000000     100.000000    3300.000000

In [15]:
df.dtypes

Unnamed: 0                 int64
country                   object
description               object
designation               object
points                     int64
price                    float64
province                  object
region_1                  object
region_2                  object
taster_name               object
taster_twitter_handle     object
title                     object
variety                   object
winery                    object
dtype: object

# Data Cleaning

In [16]:
df.isnull().sum()

Unnamed: 0                   0
country                     63
description                  0
designation              37465
points                       0
price                     8996
province                    63
region_1                 21247
region_2                 79460
taster_name              26244
taster_twitter_handle    31213
title                        0
variety                      1
winery                       0
dtype: int64

In [17]:
df.isnull().sum().sum()

np.int64(204752)

In [20]:
(df.isnull().sum()/df.shape[0])*100

Unnamed: 0                0.000000
country                   0.048472
description               0.000000
designation              28.825661
points                    0.000000
price                     6.921544
province                  0.048472
region_1                 16.347493
region_2                 61.136715
taster_name              20.192197
taster_twitter_handle    24.015357
title                     0.000000
variety                   0.000769
winery                    0.000000
dtype: float64

In [21]:
df.notnull().sum()

Unnamed: 0               129971
country                  129908
description              129971
designation               92506
points                   129971
price                    120975
province                 129908
region_1                 108724
region_2                  50511
taster_name              103727
taster_twitter_handle     98758
title                    129971
variety                  129970
winery                   129971
dtype: int64

In [22]:
(df.notnull().sum()/df.shape[0])*100

Unnamed: 0               100.000000
country                   99.951528
description              100.000000
designation               71.174339
points                   100.000000
price                     93.078456
province                  99.951528
region_1                  83.652507
region_2                  38.863285
taster_name               79.807803
taster_twitter_handle     75.984643
title                    100.000000
variety                   99.999231
winery                   100.000000
dtype: float64

In [23]:
df.duplicated().sum()

np.int64(0)

In [24]:
df.dropna(inplace = True)

# EDA(Exploratory Data Analysis)

In [27]:
df['country'].value_counts()

country
US    22387
Name: count, dtype: int64

In [30]:
df['title'].value_counts()

title
Gloria Ferrer NV Sonoma Brut Sparkling (Sonoma County)                           6
Breathless NV Brut Sparkling (North Coast)                                       5
Seven Deadly Zins 2011 Old Vine Zinfandel (Lodi)                                 3
Korbel NV Brut Sparkling (California)                                            3
Callaway 2013 Winemaker's Reserve Roussanne (Temecula Valley)                    3
                                                                                ..
McCrea 2009 Boushey Vineyard Roussanne (Yakima Valley)                           1
Swirl 2011 Lockwood Oaks Vineyard Malbec (San Antonio Valley)                    1
Fielding Hills 2011 Tribute Riverbend Vineyard Red (Wahluke Slope)               1
Alexandria Nicole 2013 Destiny Ridge Vineyard Pinot Gris (Horse Heaven Hills)    1
Hendry 2012 Blocks 7 & 22 Zinfandel (Napa Valley)                                1
Name: count, Length: 20425, dtype: int64

In [33]:
df.groupby('price')['points'].sum()

price
4.0         83
5.0        257
7.0       1105
8.0       5420
9.0       4139
          ...
350.0       90
500.0       93
625.0       94
750.0       92
2013.0      91
Name: points, Length: 146, dtype: int64

In [35]:
df['price'].sum()

np.float64(928286.0)

In [36]:
df.groupby('region_1')['region_2'].sum()

region_1
Adelaida District      Central CoastCentral CoastCentral CoastCentral...
Alexander Valley       SonomaSonomaSonomaSonomaSonomaSonomaSonomaSono...
Alta Mesa              Central ValleyCentral ValleyCentral ValleyCent...
Amador County          Sierra FoothillsSierra FoothillsSierra Foothil...
Ancient Lakes          Columbia ValleyColumbia ValleyColumbia ValleyC...
                                             ...
Yamhill County                        Willamette ValleyWillamette Valley
Yolo County            Central ValleyCentral ValleyCentral ValleyCent...
York Mountain                                              Central Coast
Yorkville Highlands    North CoastNorth CoastNorth CoastNorth CoastNo...
Yountville             NapaNapaNapaNapaNapaNapaNapaNapaNapaNapaNapaNa...
Name: region_2, Length: 171, dtype: object

# Data Visualization